apiVersion: v1
kind: ConfigMap
metadata:
  name: fcg-users-config
  namespace: default
data:
  # Logging Configuration
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"

  # JWT Configuration
  Jwt__Issuer: "fcg-users"

  # API Configuration
  AllowedHosts: "*"

  # ServiceBus Configuration
  ServiceBus__NotificationQueueName: "notifications-queue"

  # Swagger/API Documentation
  ApiTitle: "fcg-users.API"
  ApiVersion: "v1"
