apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcgusers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fcgusers
  template:
    metadata:
      labels:
        app: fcgusers
    spec:
      containers:
        - name: fcgusers
          image: arthur1702/fcgusers:latest
          ports:
            - containerPort: 80
