apiVersion: v1
kind: Secret
metadata:
  name: fcg-users-secret
  namespace: default
type: Opaque
stringData:
  # JWT Secret Key
  Jwt__Key: ${JWT_SECRET_KEY}

  # Database Connection String (Full)
  ConnectionStrings__FCGUsersDbConnection: "${DB_CONN_USERS}"

  # Service Bus Connection String
  ServiceBus__ConnectionString: ${SERVICEBUS_CONNECTION_STRING}
