name: Pipeline FCG USERS API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_EMAIL }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t arthur1702/fcgusers:latest .
          docker push arthur1702/fcgusers:latest

      # - name: Set up kubectl
      #   uses: azure/k8s-set-context@v1
      #   with:
      #     method: 'kubeconfig'
      #     kubeconfig: ${{ secrets.KUBE_CONFIG }}
      #     version: 1.21.0

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8/deployment.yaml
